# Generated by Django 5.0.2 on 2024-02-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('qts', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('qts_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(default=0, verbose_name='Краткое описание')),
                ('cooking_time', models.IntegerField(default=0, verbose_name='Время готовки')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='recipes_img/', verbose_name='Изображение')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_of_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('category', models.ManyToManyField(to='recipes.category', verbose_name='Категория')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredients', verbose_name='Ингридиенты')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
