# Generated by Django 5.0.2 on 2024-02-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_ingredients_recipe_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='qts',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='qts_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='qts',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
