# Generated by Django 5.0.2 on 2024-02-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_qts_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='qts_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='qts',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.DeleteModel(
            name='WeightType',
        ),
    ]
